call git config --global user.email "reanpuhalovich@gmail.com"
call git config --global user.name "Ryan Puhalovich"

call git config --global alias.s "status"
call git config --global alias.a "add --all"
call git config --global alias.c "commit -m"
call git config --global alias.ch "checkout"
call git config --global alias.r "rebase --interactive"
call git config --global alias.subup "submodule --init --recursive"
call git config --global alias.clonerec "clone --recursive"
