call git config --global alias.a "add --all"
call git config --global alias.c "commit -m"
call git config --global alias.r "rebase --interactive"
call git config --global alias.subup "submodule --init --recursive"
call git config --global alias.clonerec "clone --recursive"
