call git config --global user.email "reanpuhalovich@gmail.com"
call git config --global user.name "rpuhalovich"

call git config --global alias.s "status"
call git config --global alias.b "branch"
call git config --global alias.c "!sh -c 'git add -A && git commit -m \"$1\"' -"
call git config --global alias.ch "checkout"
call git config --global alias.m "merge"
call git config --global alias.r "rebase --interactive"
call git config --global alias.l "log --graph --oneline --decorate"
call git config --global alias.bl "blame -w -L"
call git config --global alias.subup "submodule --init --recursive"
call git config --global alias.clonerec "clone --recursive"
