git config --global user.email "reanpuhalovich@gmail.com"
git config --global user.name "Ryan Puhalovich"

git config --global alias.s "status"
git config --global alias.a "add --all"
git config --global alias.c "commit -m"
git config --global alias.ch "checkout"
git config --global alias.m "merge"
git config --global alias.r "rebase --interactive"
git config --global alias.l "git log --graph --oneline --decorate"
git config --global alias.subup "submodule --init --recursive"
git config --global alias.clonerec "clone --recursive"
